### ISSUE TITLE
config.json & mattermost.jinja template doesn't match

### ISSUE THREAD

**Issue by Strade28** [kjkeane/mattermost-formula#13]
Hello it seam that the mattermost.jinja template does not match to the default config.json configuration file provide by mattermost.
Is this the expected behavior ?
If not I can Make a PR for that.

Thank you for your work, by the way

**Comment by kjkeane** [comment]
It is not, I am usually busy and try to just update the template as best I can.  If there are any missing configurations or updates that need to be applied just let me know or you can open a PR.

**Comment by kjkeane** [comment]
@Strade28 This should be fixed in #14 

If there are any issues please let me know.
